name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: itsmrnatural
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          
          # Display achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          
          # Add programming languages statistics
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: recently-used
          plugin_languages_colors: github
          plugin_languages_threshold: 5%
          plugin_languages_limit: 8
          
          # Add Anilist plugin for anime statistics - only current watches
          plugin_anilist: yes
          plugin_anilist_user: itsmrnatural
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: watching, reading  # Only show currently watching/reading
          plugin_anilist_limit: 4  # Show up to 4 items per section
          plugin_anilist_shuffle: yes  # Randomly select entries if you have more than the limit
