name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: itsmrnatural
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          
          # Display achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          plugin_achievements_secrets: true
          
          # Add programming languages statistics
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: recently-used
          plugin_languages_colors: github
          plugin_languages_threshold: 5%
          plugin_languages_limit: 8

          # Recent Activities
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_visibility: public
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

          # Code Snippet
          plugin_code: yes
          plugin_code_days: 0
          plugin_code_lines: 7
          
